# Generated by Django 5.2.8 on 2025-11-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_product_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc_code',
            field=models.IntegerField(unique=True),
        ),
    ]
